export const MINERAL_MINING_ENERGY_NEEDED = 15000;
export const BASE_LINK_GREEDY_LIMIT = 20000;

export const FULL_UPGRADER_ENERGY_NEEDED = 80000;

export const TERMINAL_ENERGY_MIN = 30000;
export const TERMINAL_ENERGY_MAX = 40000;
export const TERMINAL_MINERAL_MIN = 6000;
export const TERMINAL_MINERAL_MAX = 12000;
export const TERMINAL_BOOST_MIN = 1000;
export const TERMINAL_BOOST_MAX = 5000;
export const TERMINAL_COMMODITY_MIN = 1000;
export const TERMINAL_COMMODITY_MAX = 5000;

export const FACTORY_ENERGY_MIN = 5000;
export const FACTORY_ENERGY_MAX = 10000;

export const TERMINAL_ENERGY_IMPORT_LIMIT = 10000; 
export const TERMINAL_ENERGY_EXPORT_LIMIT = 200000;

export const TERMINAL_MINERAL_NEED = 10000;
export const MINERALS:ResourceConstant[] = [
    RESOURCE_HYDROGEN,
    RESOURCE_OXYGEN,
    RESOURCE_UTRIUM,
    RESOURCE_KEANIUM,
    RESOURCE_LEMERGIUM,
    RESOURCE_ZYNTHIUM,
    RESOURCE_CATALYST
]

export const ROOM_MINERAL_IMPORT_LIMIT = 9000;
export const ROOM_MINERAL_EXPORT_LIMIT = 18000;

export const ROOM_ENERGY_IMPORT_LIMIT = 60000;
export const ROOM_ENERGY_EXPORT_LIMIT = 200000;

export const RAMPART_PERCENTAGE_MIN = 0.03;
export const RAMPART_PERCENTAGE_MAX = 0.04;